package com.PokeBox.data.postgres;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;

import com.PokeBox.beans.Pokemon;
import com.PokeBox.data.PokemonDAO;
import com.PokeBox.utils.ConnectionUtil;


public class PokemonPostgres implements PokemonDAO{
	private ConnectionUtil connUtil = ConnectionUtil.getConnectionUtil();
	//create new pokemon. NOTE: TRAINER MUST BE REGESTERED FOR EXAMPLE TESTS ONLY 3 TRAINERS ARE IN DATA BASE
	@Override
	public int create(Pokemon dataToAdd) {
	int generatedId = 0;
		
		// try-with-resources auto-closes resources
		try (Connection conn = connUtil.getConnection()) {
			// when you run DML statements, you want to manage the TCL
			conn.setAutoCommit(false);
			
			String sql = "insert into pokemon (id,health,exp,lv,type,name,item,trainer) "
					+ "values (default, ?, ?, ?, ?,?,?,?)";
			String[] keys = {"id"}; // the name of the primary key column that will be autogenerated
			// creating the prepared statement
			PreparedStatement pStmt = conn.prepareStatement(sql, keys);
			// we need to set the values of the question marks
			pStmt.setInt(1, dataToAdd.getHealth()); // question mark index starts at 1
			pStmt.setInt(2, dataToAdd.getExp());
			pStmt.setInt(3, dataToAdd.getLevel());
			pStmt.setString(4, dataToAdd.getType());
			pStmt.setString(5, dataToAdd.getName());
			pStmt.setString(6, dataToAdd.getItem());
			pStmt.setString(6, dataToAdd.getTrainer());
			
			// after setting the values, we can run the statement
			pStmt.executeUpdate();
			ResultSet resultSet = pStmt.getGeneratedKeys();
			
			if (resultSet.next()) { // "next" goes to the next row in the result set (or the first row)
				// getting the ID value from the result set
				generatedId = resultSet.getInt("id");
				conn.commit(); // running the TCL commit statement
			} else {
				conn.rollback();
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		
		return generatedId;
	}
//get all pokemon
	@Override
	public Set<Pokemon> getAll() {
Set<Pokemon> allPokemon = new HashSet<>();
		
		try (Connection conn = connUtil.getConnection()) {
			String sql = "select * from pokemon";
			Statement stmt = conn.createStatement();
			ResultSet resultSet = stmt.executeQuery(sql);
			
			// while the result set has another row
			while (resultSet.next()) {
				// create the Pokemon object
				Pokemon poke = new Pokemon();
				// pull the data from each row in the result set
				// and put it into the java object so that we can use it here
				poke.setId(resultSet.getInt("id"));
				poke.setName(resultSet.getString("name"));
				poke.setLevel(resultSet.getInt("lv"));
				poke.setType(resultSet.getString("type"));
				poke.setItem(resultSet.getString("item"));
				poke.setExp(resultSet.getInt("exp"));
				poke.setTrainer(resultSet.getString("trainer"));
				
				allPokemon.add(poke);
			}
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return allPokemon;
	}
//updates pokemon. Trainer is not to be updated as it should never change within the box
	@Override
	public void update(Pokemon dataToUpdate) {
		try (Connection conn = connUtil.getConnection()) {
			conn.setAutoCommit(false);
			
			String sql = "update pokemon set "
					+ "health=?,exp=?,lv=?,type=?,name=?,item=? "
					+ "where id=?";
			PreparedStatement pStmt = conn.prepareStatement(sql);
			pStmt.setInt(1, dataToUpdate.getHealth());
			pStmt.setInt(2, dataToUpdate.getExp());
			pStmt.setInt(3, dataToUpdate.getLevel());
			pStmt.setString(4, dataToUpdate.getType());
			pStmt.setString(5, dataToUpdate.getName());
			pStmt.setString(6, dataToUpdate.getItem());
			//trainer may not be update since in data trainer is a foreign key 
			
			int rowsAffected = pStmt.executeUpdate();
			
			if (rowsAffected==1) {
				conn.commit();
			} else {
				conn.rollback();
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	@Override
	public void delete(Pokemon dataToDelete) {
		// TODO Auto-generated method stub
		
	}
	// Gets pokemon whose level that is greater than the level provided
	@Override
	public Set<Pokemon> getByLevel(int level) {
		Set<Pokemon> allPokemon = new HashSet<>();

		try (Connection conn = connUtil.getConnection()) {
			String sql = "select * from pokemon where lv>?";
			PreparedStatement pStmt = conn.prepareStatement(sql);
			pStmt.setInt(1, level);
	
			ResultSet resultSet = pStmt.executeQuery();

			// while the result set has another row
			while (resultSet.next()) {
				// create the pokemon object
				Pokemon poke = new Pokemon();
				// pull the data from each row in the result set
				// and put it into the java object so that we can use it here
				poke.setId(resultSet.getInt("id"));
				poke.setName(resultSet.getString("name"));
				poke.setLevel(resultSet.getInt("lv"));
				poke.setType(resultSet.getString("type"));
				poke.setItem(resultSet.getString("item"));
				poke.setExp(resultSet.getInt("exp"));
				poke.setTrainer(resultSet.getString("trainer"));

				allPokemon.add(poke);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		return allPokemon;

	}
//gets by id generated
	@Override
	public Pokemon getByID(int id) {
	Pokemon poke = new Pokemon();
		
		try (Connection conn = connUtil.getConnection()) {
			String sql = "select * from pokemon where id=?";
			PreparedStatement pStmt = conn.prepareStatement(sql);
			pStmt.setInt(1, id);
			
			ResultSet resultSet = pStmt.executeQuery();
			
			if (resultSet.next()) {
				
				poke.setId(resultSet.getInt("id"));
				poke.setName(resultSet.getString("name"));
				poke.setLevel(resultSet.getInt("lv"));
				poke.setType(resultSet.getString("type"));
				poke.setItem(resultSet.getString("item"));
				poke.setExp(resultSet.getInt("exp"));
				poke.setTrainer(resultSet.getString("trainer"));
			}
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return poke;
	}
//gets all pokemon with items.
	@Override
	public Set<Pokemon> getByHasItem() {
		Set<Pokemon> allPokemon = new HashSet<>();

		try (Connection conn = connUtil.getConnection()) {
			Statement pStmt = conn.createStatement();
	
			ResultSet resultSet = pStmt.executeQuery("select * from pokemon where item=not null");

			// while the result set has another row
			while (resultSet.next()) {
				// create the Pokemon object
				Pokemon poke = new Pokemon();
				// pull the data from each row in the result set
				// and put it into the java object so that we can use it here
				poke.setId(resultSet.getInt("id"));
				poke.setName(resultSet.getString("name"));
				poke.setLevel(resultSet.getInt("lv"));
				poke.setType(resultSet.getString("type"));
				poke.setItem(resultSet.getString("item"));
				poke.setExp(resultSet.getInt("exp"));
				poke.setTrainer(resultSet.getString("trainer"));

				allPokemon.add(poke);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		return allPokemon;

	}

}
